from __future__ import annotations

PROTOCOL_VERSION = 1
BOOTSTRAP_ID = "bootstrap"

MSG_REGISTER = "REGISTER"
MSG_UNREGISTER = "UNREGISTER"
MSG_GET_PEERS = "GET_PEERS"
MSG_PEER_LIST = "PEER_LIST"
MSG_HEARTBEAT = "HEARTBEAT"
MSG_CHAT = "CHAT"
MSG_GROUP_CHAT = "GROUP_CHAT"
MSG_ACK = "ACK"
MSG_PEER_JOINED = "PEER_JOINED"
MSG_PEER_LEFT = "PEER_LEFT"
MSG_PEER_EXCHANGE = "PEER_EXCHANGE"
MSG_PEER_HELLO = "PEER_HELLO"
MSG_SYNC_REQUEST = "SYNC_REQUEST"
MSG_SYNC_RESPONSE = "SYNC_RESPONSE"

REQUIRED_FIELDS = {"type", "from", "timestamp", "message_id", "version"}
